name: Run Tests
on:
  push: {}
jobs:
  build:
    name: Tests (go ${{ matrix.go }} / ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ["^1.19", "~1.17"]
    steps:
      - name: Configure Git
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: |
          go test -cover ./...
      - name: Lint with goimports-wasabi
        run: |
          go run . -w .
          if [[ $(git status --porcelain) ]]; then
            git diff
            exit 1
          fi
        shell: bash
